import type { WorkspaceDefinition } from "./contracts";

export const trialFinderWorkspace: WorkspaceDefinition = {
  id: "clinical-trials.trial-finder",
  title: "Trial Finder Workspace",
  description:
    "A chat-first agent workspace for finding, reviewing, selecting, and managing clinical-trial pursuits for a patient.",
  primarySkill: "trial-matching",
  defaultSurfaces: [
    {
      id: "chat",
      title: "Agent Chat",
      role: "chat",
      defaultOpen: true,
      defaultWidth: 520,
      minWidth: 360,
      canCollapse: false,
      canFullscreen: true,
      mobileMode: "stack",
    },
    {
      id: "trial-candidates",
      title: "Candidate Trials",
      role: "canvas",
      defaultOpen: true,
      defaultWidth: 520,
      minWidth: 380,
      canCollapse: true,
      canFullscreen: true,
      mobileMode: "drawer",
    },
    {
      id: "trial-detail",
      title: "Trial Detail",
      role: "canvas",
      defaultOpen: true,
      defaultWidth: 480,
      minWidth: 360,
      canCollapse: true,
      canFullscreen: true,
      mobileMode: "drawer",
    },
    {
      id: "pursuit-board",
      title: "Pursuit Board",
      role: "management",
      defaultOpen: false,
      defaultWidth: 620,
      minWidth: 420,
      canCollapse: true,
      canFullscreen: true,
      mobileMode: "drawer",
    },
    {
      id: "agent-inspector",
      title: "Agent Inspector",
      role: "inspector",
      defaultOpen: false,
      defaultWidth: 420,
      minWidth: 340,
      canCollapse: true,
      canFullscreen: true,
      mobileMode: "drawer",
    },
  ],
  tools: [
    {
      id: "patient.query_sql",
      label: "Query patient warehouse",
      category: "patient",
      permission: "read",
      description: "Read-only SQL-on-FHIR queries against the selected patient's structured record.",
    },
    {
      id: "clinical_trials.search",
      label: "Search trial registry",
      category: "clinical-trial",
      permission: "external",
      description: "Search configured clinical-trial registries, starting with ClinicalTrials.gov.",
    },
    {
      id: "clinical_trials.fetch_detail",
      label: "Fetch trial detail",
      category: "clinical-trial",
      permission: "external",
      description: "Fetch full trial details and criteria for a candidate trial.",
    },
    {
      id: "trial_pursuit.upsert",
      label: "Create or update pursuit",
      category: "pursuit",
      permission: "write",
      description: "Create or update a durable trial pursuit record for the selected patient.",
    },
    {
      id: "artifact.create_packet",
      label: "Create packet draft",
      category: "artifact",
      permission: "write",
      description: "Generate a packet draft from selected patient facts, trial criteria, and source citations.",
    },
    {
      id: "transparency.export_run",
      label: "Export run bundle",
      category: "transparency",
      permission: "read",
      description: "Export messages, tool calls, context, artifacts, and source snapshots for review.",
    },
  ],
  sourceGroups: [
    {
      id: "patient-context",
      label: "Patient context",
      description: "Local patient facts and citations compiled from the selected health record.",
      sources: [
        {
          id: "sof",
          label: "SQL-on-FHIR warehouse",
          kind: "database",
          location: "data/sof.db",
          permission: "read",
        },
      ],
    },
    {
      id: "trial-registries",
      label: "Clinical-trial registries",
      description: "External trial sources searched and snapshotted by the agent.",
      sources: [
        {
          id: "clinicaltrials-gov",
          label: "ClinicalTrials.gov",
          kind: "api",
          location: "https://clinicaltrials.gov/data-api",
          permission: "external",
        },
      ],
    },
  ],
};
