"""
Pydantic response models for the EHI Ignite API.

These are the shapes returned to the React frontend. They are derived from
the Python dataclasses in fhir_explorer/parser/models.py and
fhir_explorer/catalog/single_patient.py but are separate to keep the API
contract stable independent of internal parsing model changes.

The flat ``api/models.py`` module was split into feature-area submodules in
May 2026. This ``__init__.py`` re-exports every public name so existing
``from api.models import X`` callers continue to work without modification.

Feature submodules:

- ``patients`` — patient list / overview / timeline / encounter detail /
  key labs / safety / surgical risk / immunizations / condition acuity /
  procedures / drug-drug interactions / allergy row / care journey.
- ``corpus`` — corpus-level stats, observation distributions, allergy
  criticality, field coverage.
- ``assistant`` — provider-assistant chat request/response + trace shapes.
- ``patient_context`` — guided-intake session models.
- ``aggregation`` — patient workspaces, uploaded files, cleaning queue,
  readiness checklist, canonical patient summary.
- ``harmonize`` — cross-source harmonization (observations, conditions,
  medications, allergies, immunizations, clinical notes / artifacts),
  Provenance walks, run summaries, review decisions, published-chart
  snapshots, and the guest-harmonization unauthenticated demo variants.
- ``caspian`` — workflow runs + Caspian file workspace, plus the
  re-exported ``Capabilities`` policy type pulled in for the
  ``CaspianFileListResponse`` forward reference.
"""

from __future__ import annotations

from api.models.aggregation import (
    AggregationCleaningIssue,
    AggregationCleaningQueueResponse,
    AggregationCreateProfileRequest,
    AggregationCreateProfileResponse,
    AggregationDeleteResponse,
    AggregationEnvironmentResponse,
    AggregationPreparedPreviewItem,
    AggregationPreparedPreviewResponse,
    AggregationProfile,
    AggregationReadinessItem,
    AggregationReadinessResponse,
    AggregationSourceCard,
    AggregationUpdateProfileRequest,
    AggregationUploadResponse,
    AggregationUploadedFile,
    CanonicalPatientSummary,
    CanonicalSourceSummary,
)
from api.models.assistant import (
    ProviderAssistantCitation,
    ProviderAssistantContextPackage,
    ProviderAssistantRequest,
    ProviderAssistantResponse,
    ProviderAssistantTurn,
    ToolCallDetail,
    TraceDetail,
)
from api.models.caspian import (
    Capabilities,
    CaspianFileListResponse,
    CaspianFileNode,
    CaspianFileReadResponse,
    CaspianFileWriteRequest,
    CaspianFileWriteResponse,
    SaveAsNoteRequest,
    WorkflowArtifact,
    WorkflowBanner,
    WorkflowFactCell,
    WorkflowNarrativeSection,
    WorkflowRunRequest,
    WorkflowRunResponse,
    WorkflowSection,
    WorkflowTableSection,
)
from api.models.corpus import (
    AllergyCriticalityBreakdown,
    AllergySubstanceEntry,
    CorpusStats,
    FieldCoverageItem,
    FieldCoverageResponse,
    ObservationDistribution,
    ObservationDistributionsResponse,
)
from api.models.harmonize import (
    GuestHarmonizationContextRequest,
    GuestHarmonizationDeleteResponse,
    GuestHarmonizationOutput,
    GuestHarmonizationProgress,
    GuestHarmonizationProgressEvent,
    GuestHarmonizationRunResponse,
    GuestHarmonizationUploadedFile,
    HarmonizeAllergiesResponse,
    HarmonizeAllergySource,
    HarmonizeClinicalArtifact,
    HarmonizeClinicalNote,
    HarmonizeCollection,
    HarmonizeCollectionsResponse,
    HarmonizeConditionSource,
    HarmonizeConditionsResponse,
    HarmonizeContributionTotals,
    HarmonizeContributionsResponse,
    HarmonizeExtractItem,
    HarmonizeExtractJobEvent,
    HarmonizeExtractJobResponse,
    HarmonizeExtractResponse,
    HarmonizeImmunizationSource,
    HarmonizeImmunizationsResponse,
    HarmonizeLatestObservation,
    HarmonizeMedicationSource,
    HarmonizeMedicationsResponse,
    HarmonizeMergedAllergy,
    HarmonizeMergedCondition,
    HarmonizeMergedImmunization,
    HarmonizeMergedMedication,
    HarmonizeMergedObservation,
    HarmonizeObservationSource,
    HarmonizeObservationsResponse,
    HarmonizeProvenanceResponse,
    HarmonizeReviewDecisionRequest,
    HarmonizeReviewDecisionSummary,
    HarmonizeReviewEvent,
    HarmonizeRunFactCounts,
    HarmonizeRunResponse,
    HarmonizeRunReviewItem,
    HarmonizeRunSource,
    HarmonizeRunStateResponse,
    HarmonizeRunSummary,
    HarmonizeSource,
    HarmonizeSourceDiffResponse,
    HarmonizeSourceDiffSource,
    HarmonizeSourceDiffSourceTotals,
    HarmonizeSourceDiffUniqueFacts,
    HarmonizeSourceManifestResponse,
    PublishedChartChangeSummary,
    PublishedChartSnapshot,
    PublishedChartStateResponse,
)
from api.models.patient_context import (
    PatientContextExportResponse,
    PatientContextExportStatus,
    PatientContextFact,
    PatientContextGapCard,
    PatientContextSessionCreateRequest,
    PatientContextSessionResponse,
    PatientContextTurn,
    PatientContextTurnRequest,
    PatientContextTurnResponse,
)
from api.models.patients import (
    AllergyRow,
    CareJourneyResponse,
    CareTeamSummaryItem,
    ClinicalNoteItem,
    ClinicalNotesResponse,
    ConditionAcuityResponse,
    ConditionDetail,
    ConditionEpisodeItem,
    ConditionRow,
    DiagnosticReportItem,
    EncounterDetail,
    EncounterEvent,
    EncounterMarker,
    EncounterTypeSummary,
    ImmunizationItem,
    ImmunizationResponse,
    InteractionResponse,
    InteractionResult,
    KeyLabsResponse,
    LabAlertFlag,
    LabHistoryPoint,
    LabValue,
    MedRow,
    MedicationDetail,
    MedicationEpisodeItem,
    ObservationDetail,
    PatientListItem,
    PatientOverview,
    PatientRiskSummary,
    PatientRiskSummaryResponse,
    ProcedureDetail,
    ProcedureItem,
    ProcedureMarker,
    ProceduresResponse,
    RankedConditionItem,
    ResourceTypeCount,
    SafetyFlag,
    SafetyMedication,
    SafetyResponse,
    SiteOfServiceSummaryItem,
    SurgicalRiskComponent,
    SurgicalRiskResponse,
    TimelineEvent,
    TimelineMonth,
    TimelineResponse,
)

__all__ = [
    # aggregation
    "AggregationCleaningIssue",
    "AggregationCleaningQueueResponse",
    "AggregationCreateProfileRequest",
    "AggregationCreateProfileResponse",
    "AggregationDeleteResponse",
    "AggregationEnvironmentResponse",
    "AggregationPreparedPreviewItem",
    "AggregationPreparedPreviewResponse",
    "AggregationProfile",
    "AggregationReadinessItem",
    "AggregationReadinessResponse",
    "AggregationSourceCard",
    "AggregationUpdateProfileRequest",
    "AggregationUploadResponse",
    "AggregationUploadedFile",
    "CanonicalPatientSummary",
    "CanonicalSourceSummary",
    # assistant
    "ProviderAssistantCitation",
    "ProviderAssistantContextPackage",
    "ProviderAssistantRequest",
    "ProviderAssistantResponse",
    "ProviderAssistantTurn",
    "ToolCallDetail",
    "TraceDetail",
    # caspian
    "Capabilities",
    "CaspianFileListResponse",
    "CaspianFileNode",
    "CaspianFileReadResponse",
    "CaspianFileWriteRequest",
    "CaspianFileWriteResponse",
    "SaveAsNoteRequest",
    "WorkflowArtifact",
    "WorkflowBanner",
    "WorkflowFactCell",
    "WorkflowNarrativeSection",
    "WorkflowRunRequest",
    "WorkflowRunResponse",
    "WorkflowSection",
    "WorkflowTableSection",
    # corpus
    "AllergyCriticalityBreakdown",
    "AllergySubstanceEntry",
    "CorpusStats",
    "FieldCoverageItem",
    "FieldCoverageResponse",
    "ObservationDistribution",
    "ObservationDistributionsResponse",
    # harmonize
    "GuestHarmonizationContextRequest",
    "GuestHarmonizationDeleteResponse",
    "GuestHarmonizationOutput",
    "GuestHarmonizationProgress",
    "GuestHarmonizationProgressEvent",
    "GuestHarmonizationRunResponse",
    "GuestHarmonizationUploadedFile",
    "HarmonizeAllergiesResponse",
    "HarmonizeAllergySource",
    "HarmonizeClinicalArtifact",
    "HarmonizeClinicalNote",
    "HarmonizeCollection",
    "HarmonizeCollectionsResponse",
    "HarmonizeConditionSource",
    "HarmonizeConditionsResponse",
    "HarmonizeContributionTotals",
    "HarmonizeContributionsResponse",
    "HarmonizeExtractItem",
    "HarmonizeExtractJobEvent",
    "HarmonizeExtractJobResponse",
    "HarmonizeExtractResponse",
    "HarmonizeImmunizationSource",
    "HarmonizeImmunizationsResponse",
    "HarmonizeLatestObservation",
    "HarmonizeMedicationSource",
    "HarmonizeMedicationsResponse",
    "HarmonizeMergedAllergy",
    "HarmonizeMergedCondition",
    "HarmonizeMergedImmunization",
    "HarmonizeMergedMedication",
    "HarmonizeMergedObservation",
    "HarmonizeObservationSource",
    "HarmonizeObservationsResponse",
    "HarmonizeProvenanceResponse",
    "HarmonizeReviewDecisionRequest",
    "HarmonizeReviewDecisionSummary",
    "HarmonizeReviewEvent",
    "HarmonizeRunFactCounts",
    "HarmonizeRunResponse",
    "HarmonizeRunReviewItem",
    "HarmonizeRunSource",
    "HarmonizeRunStateResponse",
    "HarmonizeRunSummary",
    "HarmonizeSource",
    "HarmonizeSourceDiffResponse",
    "HarmonizeSourceDiffSource",
    "HarmonizeSourceDiffSourceTotals",
    "HarmonizeSourceDiffUniqueFacts",
    "HarmonizeSourceManifestResponse",
    "PublishedChartChangeSummary",
    "PublishedChartSnapshot",
    "PublishedChartStateResponse",
    # patient_context
    "PatientContextExportResponse",
    "PatientContextExportStatus",
    "PatientContextFact",
    "PatientContextGapCard",
    "PatientContextSessionCreateRequest",
    "PatientContextSessionResponse",
    "PatientContextTurn",
    "PatientContextTurnRequest",
    "PatientContextTurnResponse",
    # patients
    "AllergyRow",
    "CareJourneyResponse",
    "CareTeamSummaryItem",
    "ClinicalNoteItem",
    "ClinicalNotesResponse",
    "ConditionAcuityResponse",
    "ConditionDetail",
    "ConditionEpisodeItem",
    "ConditionRow",
    "DiagnosticReportItem",
    "EncounterDetail",
    "EncounterEvent",
    "EncounterMarker",
    "EncounterTypeSummary",
    "ImmunizationItem",
    "ImmunizationResponse",
    "InteractionResponse",
    "InteractionResult",
    "KeyLabsResponse",
    "LabAlertFlag",
    "LabHistoryPoint",
    "LabValue",
    "MedRow",
    "MedicationDetail",
    "MedicationEpisodeItem",
    "ObservationDetail",
    "PatientListItem",
    "PatientOverview",
    "PatientRiskSummary",
    "PatientRiskSummaryResponse",
    "ProcedureDetail",
    "ProcedureItem",
    "ProcedureMarker",
    "ProceduresResponse",
    "RankedConditionItem",
    "ResourceTypeCount",
    "SafetyFlag",
    "SafetyMedication",
    "SafetyResponse",
    "SiteOfServiceSummaryItem",
    "SurgicalRiskComponent",
    "SurgicalRiskResponse",
    "TimelineEvent",
    "TimelineMonth",
    "TimelineResponse",
]
